name: prevent_app_screen
description: A Flutter plugin to prevent screenshots and screen recordings on Android, iOS, macOS, Windows, Linux, and Web.
version: 0.1.1
homepage: https://github.com/Mahmoud-t0lba/screen_shot

environment:
  sdk: ^3.6.0
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.4
  flutter_web_plugins:
    sdk: flutter
  web: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.prevent_app_screen
        pluginClass: PreventAppScreenPlugin
      ios:
        pluginClass: PreventAppScreenPlugin
      macos:
        pluginClass: PreventAppScreenPlugin
      windows:
        pluginClass: PreventAppScreenPlugin
      linux:
        pluginClass: PreventAppScreenPlugin
      web:
        pluginClass: PreventAppScreenWeb
        fileName: prevent_app_screen_web.dart
